os:
  - linux

language: cpp

sudo: required
services:
  - docker

before_install:
  - docker pull thecruel/cpp3ds

script:
  - docker run --rm -v "$PWD":/usr/project -w /usr/project thecruel/cpp3ds sh .build.sh
